### ISSUE TITLE
jit.mo.time @speed < 0 : output range is -3. -1.

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/jit.mo#30]
jit.mo.time @mode function  @speed -1
output range is -3. -1. (instead of -1. 1.)

I would expect it to stay in the same range [-1. 1.]

<pre><code>
----------begin_max5_patcher----------
1191.3oc4YkriiaCD8rGf4ePPmsM3h01fbnmbI.AHmxoff.CYaZa1PRzfhZb
OYP92SQRI4ktsL8hZzNoOzhllj0qdEYUOQ+iO+oA9yDuvJ889h2e5MXvOfdF
X5S2yflNF3mm9x7rzRy.8SUJYE2eX82sQxJYEpTEWTLUxlqrqFEMYLZnGkln
efCP5GDxXj2e0LS9By5Il87HLoc8DUpLlR88ML6B46uaFkpumY51em4SUyWy
KVcYlV6Cl0ojox4Ef+0tfEUPG.BLNKduds.y1so2+4yeR+DdLzYxatHOGXqV
qoXuXPs+10rBuxML1BuexCM1Cr1lJkmLsXEyiW5MhN1aDd7Yocbfw2SL9NAa
XBB5TzNx+Bo1yu7tvenql+xqxT7xL9Bl7bTAlP2eaPD17.c.X2jJSyYJlbJq
Hclk.PsTR6dCy5MxrbPLXu4CCok3nuAAOois0Cuhs1t3StD.HWc.XYl.Vpyw
8AgFXNw.y25.XmD+dDXP2D3L33wEShmEbKEx7TyfCeeHUkX0J.3tsglDjXOC
17+KmUCOMqxgjSW4txN.V+lT0sJR3Ha1pH6YGRbmUjhtiEjbvx6JHoKAblhQ
5hFS2xWnVa1ipI+6LiVv1BjvqqR8LWMNWLVwyYdOkKVv7VVULWSzdOY2x4g8
dxVFaDZLw0bzn5GAcFShukroyEYBocznwSRP3jvglVwHZhtU.NJbRDDeN7D0
IyA2Al62rEcEb1JjYK7xE6BGNFBvQVwRjNi.TGRGeC005.DtPoz2QYE3I2fr
ht0Lf5GQCch3ONhFvA2rnAZRuoZnCz8wV0P3MKZHneTMD9HHZH1IMCA8fng3
+WoYvcICXrSRFnQejzLzEn62bEWzk1zTo3bWZC99eoMcY567k1XWX+LdwqtA
LC9zewQTZonRNuwEat2Ju8f3BVohWXn08F0D6fNcvyc6gcxdn6lAiu.+qcyf
TKip6q4wY.D5B.hua9az6q4bhdCNA8huC.fFcIan5kHbfSg3FfdOLXz6rAci
j0pVcJNWm3Jcyluwjk0Kh05PR+msUrhGZ+Luv9Ya4deI6a7loT2UpDxEqfDw
URaZ5WBqu1Rec0ZYAT2nFEZ+WaZSJ8iSZV.pHMy+qUK3heGJtTUN82XEU0Yo
A2dYJ7dVGwVyVsjmk0VocvtuBzPTWPotP7vl9OntLIYBFGqqFSwzHhoBMEZD
D.0QZoy5IgaqlG.0yIlp4gjnIAlVwDZ.U2Bc77H6rViJ.JBjALw1B5BenJ.f
WKVYq6QhPspszkdEaDxlXOL4jcynBjzKSWv0+BAsmtZh7MruUxNLjWUX09Zr
sy7vcqsgmeMMWjmNcMeEr4c0ZEawTg4mYn63T574fM2i4MuFIHAxvW0N+8Dm
qYYafsFroYoyXYivcCukBvP7+t9XmVm09uYVgpYYgCaeUxSy1SfhVo5A6nBp
imuUq6taZkM+yYUry4huJBn2wa0ehFG1teNQ2UOiTxCCRoOBH8WjLVwUD9sG
.o5+zsvgwPtrdFkjGBTR+fix+fkkI1dEg7XB7NmZ.FEiiMYlPAIA55W3iS4s
W5PhdTHTbO5Jj+63JzGFWQOS3w+Brve2J
-----------end_max5_patcher-----------
</code></pre>

**Comment by pixlpa** [comment]
This appears to only happen with the "line" function. Other functions work as expected.

**Comment by robtherich** [comment]
forgot to tag, should be fixed with 38c9d91
