### ISSUE TITLE
jit.time.line incorrect timing

### ISSUE THREAD

**Issue by liuboto** [Cycling74/jit.mo#31]
sending (start 0., end 1., interval 5000, speed 1, phase 0)  to [jit.time.line] should ramp from 0 to 1 in 5 seconds according to help. however it takes approximately 500ms.
speed and time seem to be correlated incorrectly. from my tests it looks like the formula is

0.1*interval/speed ~= ramptime

the 0.1 seems arbitrary. here is a patch

<pre><code>
----------begin_max5_patcher----------
1406.3ocyYssaiaCD8YmuBB8TagWWdQWKvVj12KZA5KEnYQ.sMcrBjnDjnyk
tX+26PRIG6XYKYaZmcePZEMkFdNyLGNCyWuYj2zhWD0dneA8unQi95MiFYFR
OvnlmG4kyeYVFu1LMuYE44Boxar82ThWTlwUUuhTKE0Bzm901erjqlsLU9v8
UhYJqQBwgSviQAw5qDbf9FEOAi9Ry6HWkmJyDJi0HuMXwJU6n3lQSmarbwzG
+DMwSO12t4F8kwmIVRkJQ0S7LDWNGUWJDvUgHGMqnpRjwUvyKJpzvEwmoVAS
TklKPEKLCUwyKmfDuTBfFl4TwR9SovzQq+re1LGy6n+NFK7Yxj6jESqgYrwK
cmDOg7S+P6a9ylo9ia7AZW6YoRwrhURC.B2O+GDyzTNi3ab.IT8s3ny2AD4R
GfkG3pzBYMpPh9ie+uHwnzDze92+CAXD+CDgE2DTkXuQhbUHVvofvbQcM+Aw
NHrVwqTH7jwHADiQf6qiNHX3eiah6f0cvXT4RNjXg6zYSaohJH4SpLj18cOi
cIqnDhINfZBGn9XSvQv9HKZmjEoCxhztVsyS8ZovZQOOzWbXjhk1PnF5xjHd
mDE.THBHOBbEg7ShYaLHMPOHEi8WOHvBsy7NowAXXd8PIIIzNI9fdiAYTSvG
IvPqQ9meLH9JECFrUHHYmHvtTVHFLSX1DtvDyM5YGJQhcbnzzUJUg7.HgEa1
ihDFaSJZudLNut.Rza1DjuE.UeuPxmlI1zauCHmxkObZ.kqTUqR6eyXBrm.H
xPHrC6xHaD.c+yoyUKMa1neqCQA5kwVaq50A2D3Xm7YGyS2U18jTX8sawRv1
7gXlqRK7cLiIEOCe2cqqCDTq5OYw2OtcqiiGdzNfGauvaQVAG1H3TwI75f0O
.hnLKhrNtnAlT.Exky2p5q9wH9jDDzP+zEE5U8qA918rbl320V66Dila88tN
Z9REL2q2zOLRqsyhnN0c5iu19yU4SOnmyOnowF7FQuziCnc34Xwe.4n6I3c1
R3KJF.GvL60XigOVNf0AGD5cHblJUs2tLBxsawzHHGbwDjo9e.N6dgOwVXMM
H4XhrOk8iHe.veeEpoqYZBxGpIqepgDYz0BoNp1pjqSoU5RHgJMGfq2Jp4SN
L9XC0Qe37Ymqa8XpZxyEUYyQ2ZCmPj9EwnFHSHDWIh0OlubkT1hoH7ENEl9c
TF7.a0ZPGtPCAFi2PIzAI5ggNNSu2Vt8aNvsqTK2FJti9sYrqT+186ZiXaxH
Atp+XF85HhqE2zcULwnleaaPuVpSGzCiXixQ2lUTTNjfbJMzJVvbTMrT5A09
7V+4mUjUTY+E7jDLIIDRNwSh0WXITRPjdSY7Vzm4kMak8t+LRF.pGeaNstXU
0rVy2dTwn2f3bQsJUZNikMlj9ry1XREUyElEJoSGoSMsl85xz3yxz5S076YS
eYH7nAXYsl7E.zCwz5CcBg2i5vfsj+GF89Np6ZZZ8A3drwy4oyKKfZBZDNBg
hcCzE6FXN7Uenb90OdM7IWnrM1PLsuCB7zmIyvBwImKcNDCgc.jFTR6GkPUR
2FlddovV2SuH9bcgICQI1AdvAIIcYx7FjXHwAXjMjMTYtfMYCI7v2EYdL1Yq
mCM4cozyYziX0cdkHNHK4BCMjXn3cLjs7adY4Shp5lYarAz7xi1h4iGadLUZ
ezz4nWk3oz14aZjviWA8inflQVUYVWduDZONTu7BHeTBs0ZkUAzAlrV8Z16K
4Wxysu5RQV4hzLw8Y7ohr1+7G.pVvWko1lIVTHUsuHfyeqJkm8VKI59r1psj
f0skr6+irQqR5Oac5+07Y08Y2xaia7KUBXFZTXVxMKwbX8k1p8zRull.0qw5
Rt0oY5U7lucy+CzRnU.L
-----------end_max5_patcher-----------
</code></pre>

**Comment by robtherich** [comment]
couple problems here, 1 is a bug or two, but 2 is a misunderstanding of how interval works due to a lack of documentation. if interval is non-zero, it will overwrite the speed attribute according to its value. you can't set both speed and interval, it's one or the other.
