### ISSUE TITLE
Opening inspector for jit.time.line, jit.mo.time and jit.mo.join crashes Max

### ISSUE THREAD

**Issue by ashleybellouinc74** [Cycling74/jit.mo#32]
If you open the inspector for jit.time.line, jit.mo.time or jit.mo.join, Max 8.0.2 will crash instantly.

**Comment by tap** [comment]
ouch! i can repro... looking into it...

**Comment by tap** [comment]
This is now fixed -- will be in the Package Manager shortly as v1.1.1 -- the problem was that an experimental ITM branch was accidentally being used for the Min API instead of the Master Branch.

**Comment by ashleybellouinc74** [comment]
Thanks for the quick fix, Tim!
