### ISSUE TITLE
FR: jit.mo.function - do not reset to start value in non-loop mode

### ISSUE THREAD

**Issue by corymetcalf** [Cycling74/jit.mo#35]
When jit.mo.function finishes its loop, the final value is the start value instead of the end value. It seems like it should really stop at the end value. This would make line mode and saw mode much more useful.

**Comment by robtherich** [comment]
line seems to do the right thing, I only notice this incorrect behavior with saw. also I assume we're talking about jit.mo.time, not jit.mo.function?
