### ISSUE TITLE
readme needs to be fleshed out

### ISSUE THREAD

**Issue by tap** [Cycling74/jit.mo#8]

**Comment by wasawi** [comment]
I already have the min-devkit running.
I'd like to know where to place this repository in order to build it correctly.

Any information is appreciated,
Thank you!
j

**Comment by tap** [comment]
Hi!

If you have jit.mo (from Github) cloned into your packages folder for Max, then you should be able to follow all the same instructions as you would for the Min-DevKit. So for the Mac:

```
mkdir build
cd build
cmake -G Xcode ..
cmake --build .
```
It doesn't matter where the Min-DevKit package is installed because jit.mo will include its own copy of the Min-API as a git submodule.

Hope this helps!

**Comment by wasawi** [comment]
Thank you very much!
